@FUPostman_HostAddress = https://localhost:7184

GET {{FUPostman_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{FUPostman_HostAddress}}/Test/From
Content-Type: application/x-www-form-urlencoded

name = testName &
lastName = testSurname &
age = 24

> {%
console.log("fufu")
let responseConvert = JSON.parse(response.body)
client.global.set("Sumthing", responseConvert.Name + "jjjj")
%}
###

POST {{FUPostman_HostAddress}}/Test/From
Content-Type: application/x-www-form-urlencoded

name = {{Sumthing}} &
lastName = testSurname &
age = 24

> {%
    let responseConvert = JSON.parse(response.body)
    client.global.set("Sumthing", responseConvert.Name + "updated")
 %}
###